version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-alpine3.17
        auth:
          username: koko2000psp
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
