version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-alpine3.17
        auth:
          username: koko2000psp
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            docker build -t circle .
            docker tag circle koko2000psp/circle
  deploy:
    steps:
     - run:
        name: Deploy to Docker Hub
        command: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u koko2000psp
          docker push koko2000psp/circle
