orbs:
  docker: circleci/docker@1.7.0

version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-alpine3.17
        auth:
          username: koko2000psp
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            echo "Here in RUN"
      - docker/push:
          image: circle 
          tag: circle 
          registry: koko2000psp 
