orbs:
  docker: circleci/docker@1.7.0

version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-alpine3.17
        auth:
          username: koko2000psp
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - docker/build:
          image: circle 
          tag: koko2000psp/circle 
workflows:
    example-workflow:
      jobs:
        - docker/publish:
            docker-password: DOCKERHUB_PASSWORD 
            docker-username: koko2000psp 
            image: koko2000psp/circle 
            deploy: true 
